### ISSUE TITLE
Look into submitting adc-streaming for inclusion to conda-forge

### ISSUE THREAD

**Issue by mjuric** [astronomy-commons/genesis-client#27]
We should look into submitting `adc-streaming` to `conda-forge`, to make it easy for downstream dependences to install.

This would require creating a [feedstock](https://conda-forge.org/docs/maintainer/adding_pkgs.html) from the current recipe, and understand how we'd want to manage the in-package recipe vs. having it fully in the feedstock.

**Comment by myNameIsPatrick** [comment]
@mjuric, @spenczar, the current method for determining the version is incompatible with a conda-forge feedstock, since it requires the package to be installed from a git repository and we need to be able to install the package from an archive.

```
Running command python setup.py egg_info
    fatal: not a git repository (or any of the parent directories): .git
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-req-build-iqs0q977/setup.py", line 93, in <module>
        version=git_version(),
      File "/private/tmp/pip-req-build-iqs0q977/setup.py", line 32, in git_version
        version = check_output(command.split()).decode('utf-8').strip()
      File "/Users/runner/miniforge3/conda-bld/adc-streaming_1616459830588/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/Users/runner/miniforge3/conda-bld/adc-streaming_1616459830588/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.6/subprocess.py", line 438, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--long', '--dirty', '--always']' returned non-zero exit status 128.
```

**Comment by mjuric** [comment]
Hi Patrick, where is the draft feedstock code (to understand the problem better...)?

**Comment by myNameIsPatrick** [comment]
Here is the `meta.yaml` recipe: https://github.com/conda-forge/staged-recipes/pull/14349/files
Here are the logs for a failed job in the PR (now closed): https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=294010&view=logs&jobId=6f142865-96c3-535c-b7ea-873d86b887bd&j=e35d4f76-8ff2-5536-d795-df91e63eb9f7&t=fa7b4b17-b6ff-5c9c-8cfc-15f888c92310

**Comment by myNameIsPatrick** [comment]
Re-submitted to staged-recipes: https://github.com/conda-forge/staged-recipes/pull/16369

**Comment by myNameIsPatrick** [comment]
Now on conda-forge: https://anaconda.org/conda-forge/adc-streaming
